### ISSUE TITLE
Announcing dhall-ansible?

### ISSUE THREAD

**Issue by Gabriel439** [TristanCacqueray/dhall-ansible#1]
I just stumbled across this repository today and I was curious if you had announced it already or if it is still a work in progress

The reason I ask is that whenever you consider this repository ready, I can both announce it on Twitter and also link to it from dhall-lang.org

**Comment by TristanCacqueray** [comment]
Let me update the README with the current status and cut a 0.1.0 release.

The types are not complete, in particular the Task and Play are handwritten based on my needs. Though this is already useful and dhall-ansible could use some publicity. Not sure how it happened for dhall-kubernetes, but I would be happy to get it transfered to the dhall-lang/ organization if you wish too.

**Comment by Gabriel439** [comment]
There's no rush!  I was just curious because I don't use Ansible so I wasn't sure what a complete integration would look like.

**Comment by TristanCacqueray** [comment]
I think the core issue is that Ansible goes out of its way to feature easy composition with roles. This becomes counter-intuitive when you can use Dhall function to combine lists of task instead.

The other issue I was having was for the `vars` or `k8s.definition` attributes that support arbitrary structure, but thanks to the `dhall-manual` I now understand how to use the JSON/Type.

Finally, turns out there is a much better json schemas provided by https://github.com/SchemaStore/schemastore/tree/master/src/schemas/json , and I'd like to use them to generate better module binding per version, similarly to the `dhall-kubernetes` binding.

I'll open a PR on `awesome-dhall` when `dhall-ansible` is deemed stable, hopefully in the near future. Thank you for reaching out :-)

**Comment by TristanCacqueray** [comment]
Well I'm unsure if using `JSON/Type` for `vars` and such is the right things to do. The `v0.2.0` currently uses a simpler `List {mapKey : Text, mapValue: Text}`, and with that the binding is quite usable already. I documented this shortcoming in the README and proposed https://github.com/dhall-lang/awesome-dhall/pull/16 .

**Comment by Gabriel439** [comment]
Alright, I have a pull request to also mention `dhall-ansible` on dhall-lang.org: https://github.com/dhall-lang/dhall-lang/pull/999

**Comment by TristanCacqueray** [comment]
Thank you for the advertisement @Gabriel439 !

**Comment by Gabriel439** [comment]
@TristanCacqueray: You're welcome! :slightly_smiling_face:
